[package]
name = "psyche-core"
version = "0.1.0"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"

[dependencies]
uuid = { version = "0.7", features = ["serde", "v4"] }
rand = "0.5"
serde = { version = "1.0", features = ["derive"] }
