[package]
name = "amethyst-demo"
version = "0.2.17"
authors = ["Patryk 'PsichiX' Budzynski <psichix@gmail.com>"]
edition = "2018"

[dependencies]
amethyst = "0.10"
psyche-amethyst = { version = "0.2", path = "../psyche-amethyst" }
psyche = { version = "0.2", path = ".." }
